#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

if [ ! -f /var/www/html/app/etc/env.php && -n $MAGENTO_AUTO_INSTALL ]; then
    install
fi

exec "$@"
