<?php include "Dockerfile"; ?>

ENV MAGENTO_RUN_MODE production
ENV MAGENTO_ROOT /var/www/html

RUN a2enmod rewrite

# Get composer installed to /usr/local/bin/composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install n98-magerun2.phar and move to /usr/local/bin/
RUN curl -O https://files.magerun.net/n98-magerun2.phar && chmod +x ./n98-magerun2.phar && mv ./n98-magerun2.phar /usr/local/bin/

RUN apt-get install -y unzip vim && composer global require hirak/prestissimo

ADD bin/* /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/magento-installer", "/usr/local/bin/magento-command", "/usr/local/bin/magerun2", "/usr/local/bin/run-cron", "/usr/local/bin/pre-install"] 

# Installing cypress
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb && \
    npm install --prefix /usr/local/ cypress

ADD etc/php-apache.ini /usr/local/etc/php/conf.d/zz-magento.ini

ARG COMPOSER_MAGENTO_USERNAME
ARG COMPOSER_MAGENTO_PASSWORD
ARG COMPOSER_GITHUB_TOKEN
ARG M2SETUP_VERSION=2.3.5-p1

ENV M2SETUP_DB_HOST=127.0.0.1 \
    M2SETUP_INSTALL_DB=true \
    M2SETUP_DB_HOST=127.0.0.1 \
    M2SETUP_DB_NAME=magento2 \
    M2SETUP_DB_USER=magento2 \
    M2SETUP_DB_PASSWORD=magento2 \
    M2SETUP_BASE_URL=http://127.0.0.1/ \
    M2SETUP_BACKEND_FRONTNAME=admin \
    M2SETUP_ADMIN_FIRSTNAME=Admin \
    M2SETUP_ADMIN_LASTNAME=User \
    M2SETUP_ADMIN_EMAIL=dummy@gmail.com \
    M2SETUP_ADMIN_USER=admin \
    M2SETUP_ADMIN_PASSWORD=password123 \
    M2SETUP_USE_SAMPLE_DATA=true
    # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/ \

RUN pre-install

CMD ["apache2-foreground"]
